name: cosmotiva
description: "A premium cosmetics-analysis app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3

  flutter_secure_storage: ^9.0.0
  lottie: ^3.1.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  camera: ^0.11.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  flutter_dotenv: ^5.1.0
  uuid: ^4.4.0
  flutter_animate: ^4.5.2
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  cached_network_image: ^3.4.1
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9


flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/sample_images/
